import "src/app/styles/app.scss";
import 'react-toastify/dist/ReactToastify.css';
import type { AppProps } from 'next/app'
import { useState } from "react";
import { useRouter } from "next/router";
import GameContainer from "../app/UI/Global/GameContainer/GameContainer";
import Head from "next/head";
import { ToastContainer } from 'react-toastify';
import Script from 'next/script'

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter(),
    [game, setGame] = useState({}),
    gameContainerProps = {
      onGameLaunch(game: any) {
        setGame(game);
      },
      router, 
      onThoughtClick: (thoughtData: any) => router.push(`/thought?id=${ thoughtData.id }&hex=${ thoughtData.hex }`),
    };

  return (
    <div id="app">
      <Head>
          <title>ThoughtApp | See what others are thinking</title>
          <meta 
              name="description" 
              content="Generated by create next app" />
          <link 
              rel="icon" 
              href="/favicon.ico" />
          <link 
            rel="stylesheet" 
            href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css" />
          <Script src="https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js"></Script>
      </Head>
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={true}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        draggable />
      <GameContainer {...gameContainerProps} />
      <Component game={game} {...pageProps} />
    </div>
  );
}
export default MyApp
