import "src/app/styles/app.scss";
import type { AppProps } from 'next/app'
import { useRouter } from "next/router";
import GameContainer from "../app/UI/Global/GameContainer/GameContainer";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();

  return (
    <div id="app">
      <Head>
          <title>ThoughtApp | See what others are thinking</title>
          <meta 
              name="description" 
              content="Generated by create next app" />
          <link 
              rel="icon" 
              href="/favicon.ico" />
          <script src="https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js"></script>
      </Head>
      <GameContainer 
        router={router}
        onThoughtClick={(thoughtData: any) => router.push(`/thought?id=${ thoughtData.id }&hex=${ thoughtData.hex }`)} />
      <Component {...pageProps} />
    </div>
  );
}
export default MyApp
