import type { NextPage } from 'next'
import Head from 'next/head'
import Panel from "../app/UI/Login/Panel";
import DefaultLayout from "../app/UI/Layout/Default";

const Home: NextPage = () => {
  return (
    <DefaultLayout>
        <div className="home">
            <Head>
                <title>Home</title>
                <meta 
                    name="description" 
                    content="Generated by create next app" />
                <link 
                    rel="icon" 
                    href="/favicon.ico" />
            </Head>
            <main>
                <Panel />
            </main>
        </div>
    </DefaultLayout>
  );
}

export default Home
